### ISSUE TITLE
readLastMail request is 204, but the email is in the inbox

### ISSUE THREAD

**Issue by GonzaSSH** [mailosaur/mailosaur-node#14]
Hey there,

I have all my tests that use Mailosaur being flaky since the end of last week/beginning of this week due to Mailosaur responding 204 to the readLastMail request, although the email that I'm trying to access is there. I never encounter this issue before. Do you have any idea what could be causing this now?

**I'm using Cypress and the code of one of the tests looks like this**

```
describe('Email Confirmation', function () {
  beforeEach(() => {
    // creates an unconfirmed user through the API
    cy.login('voter').as('emailUser')
  })

it('should show email confirmation prompt and page', function () {
    cy.visit('/')
    // Opens the avatar menu
    cy.get('[data-test="navbar-account-menu"]').click()
    // Clicks on Verifizieren sie ihre E-Mail-Adresse, um alle Funktionen von Civey zu nutzen!
    cy.contains('[data-test="account-menu"] a', 'Verifizieren Sie Ihre E-Mail-Adresse').click({
      force: true
    })
    // should end up on email confirmation page
    cy.location('pathname', { timeout: 10000 }).should('equal', '/signup/verify')
    cy.task('readLastMail', {
      sentTo: this.emailUser.email,
      subject: 'Bitte bestätigen Sie Ihre E-Mail-Adresse jetzt!'
    })   
      // links to mandrill and redirects to civey.com
      .then(mail => cy.request({url: mail.html.links[0].href, followRedirect: false }))
      .then(response => {
        expect(response.headers.location).to.include('/confirm-email')

```
**The error message I get**

`CypressError: cy.task('readLastMail') failed with the following error:

> Error: Operation returned an invalid status code '204'
    at Request.self.client.request.post [as _callback] (/Users/Documents/cypress-tests/node_modules/mailosaur/lib/operations/messages.js:366:27)
    at Request.self.callback (/Users/Documents/cypress-tests/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/Documents/cypress-tests/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/Documents/cypress-tests/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

Thank you!

**Comment by andosaur** [comment]
If the email is not found within 20 seconds then the server returns 204 (No Content). The client interprets a 204 as an error.
It's possible that your search criteria is not valid.
Alternatively, either wait before calling the wait for method to give the server a bit more time, or use a loop to poll using the search method.
